In [3]:
import numpy as np
a=np.array([1,2,3])
print(type(a))             #1-D array
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(3,)
int32


In [18]:
import numpy as np
b=np.array([[1,23],[23,46],[1,23]])
print(b.shape)                     #2-D array
print(b[0,0],b[0,1],b[1,1])

(3, 2)
1 23 46


In [5]:
#FUNCTION  np.ZEROS() 
import numpy as np
c=np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [17]:
#FUNCTION np.ONES()
import numpy as np
d=np.ones((1,2))
print(d)

[[1. 1.]]


In [3]:
#FUNCTION np.FULL()
import numpy as np
d=np.full((3,2),3) #PRINTS THE SAME VALUE IN ENTIRE ARRAY
print(d)

[[3 3]
 [3 3]
 [3 3]]


In [21]:
#FUNCTION np.EYE()
import numpy as np
d=np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
#FUNCTION np.ARRAY
import numpy as np
b=np.array([[1,23,45,50],[3,4]])
print(b.shape)

(2,)


In [23]:
#FUNCTION np.RANDOM.RANDOM() OR  np.RANDOM.RAND
import numpy as np
e=np.random.random((3,3))#two brazes are important
print(e)  


[[0.66083078 0.09765014 0.79452382]
 [0.88363124 0.44590623 0.3253673 ]
 [0.70082944 0.98261912 0.21133248]]


In [3]:
#RANDOM
import numpy as np
f=np.random.rand(3,5)
print(f)

[[0.10127135 0.92460323 0.69360837 0.03234409 0.53421481]
 [0.11560611 0.18545336 0.06997421 0.06818721 0.82392458]
 [0.46185668 0.60887304 0.49561008 0.63333951 0.10260124]]


In [6]:
#RAVEL FUNCTION
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[8,8],[9,3]]])
a.ravel()
a.shape

(3, 2, 2)

In [26]:
#some of the other functions are
#sum(axis=0)  #it sums column wise
#sum(axis=1)  #it sums row wise

In [7]:
#RESHAPE
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[8,8],[9,3]]])
print(a.shape)
b=a.reshape(2,3,2)
print(b)

(3, 2, 2)
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [8 8]
  [9 3]]]


In [9]:
#TO CONCATENATE BOTH ARRAYS VERTICALLY INTO A ARRAY
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2],[3,4],[5,6]])
alldata=np.concatenate((a,b),axis=0)
print(alldata)

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [6]:
#TO CONCATENATE BOTH ARRAYS VERTICALLY INTO A ARRAY
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2],[3,4],[5,6]])
alldata=np.concatenate((a,b))
print(alldata)

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [5]:
#TO CONCATENATE BOTH ARRAYS VERTICALLY INTO A ARRAY
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2],[3,4],[5,6]])
alldata=np.concatenate((a,b),axis=1)
print(alldata)

[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]
